[package]
name = "zeo"
version = "0.1.1"
authors = ["Orson Mosley <orson.mosley@6point6.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zordon = "0.1.10"
assert_hex = "0.2.2"
byteorder = "1.4.2"